name: Build & Deploy Website
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-22.04
    env:
      EVENTBRITE_API_KEY: ${{ secrets.EVENTBRITE_API_KEY }}
    steps:
      - name: Print eventbrite api key
        run: echo "${{ secrets.EVENTBRITE_API_KEY }}"
      - uses: actions/checkout@main
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
