name: Build & Deploy Website
on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: public
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
